// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Profile struct {
	ID          int64
	Name        string
	Description string
}

type ProfileVar struct {
	ProfileID int64
	Name      string
	Value     string
	Kind      string
}
