// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"
)

const createSecret = `-- name: CreateSecret :exec
INSERT INTO secret (name, encrypted_value) VALUES (?, ?)
ON CONFLICT (name) DO UPDATE SET encrypted_value = excluded.encrypted_value
`

type CreateSecretParams struct {
	Name           string
	EncryptedValue string
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) error {
	_, err := q.db.ExecContext(ctx, createSecret, arg.Name, arg.EncryptedValue)
	return err
}

const deleteAllSecrets = `-- name: DeleteAllSecrets :exec
DELETE FROM secret
`

func (q *Queries) DeleteAllSecrets(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSecrets)
	return err
}

const deleteSecret = `-- name: DeleteSecret :execrows
DELETE FROM secret WHERE name = ?
`

func (q *Queries) DeleteSecret(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSecret, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSecret = `-- name: GetSecret :one
SELECT name, encrypted_value FROM secret WHERE name = ?
`

func (q *Queries) GetSecret(ctx context.Context, name string) (Secret, error) {
	row := q.db.QueryRowContext(ctx, getSecret, name)
	var i Secret
	err := row.Scan(&i.Name, &i.EncryptedValue)
	return i, err
}

const listSecrets = `-- name: ListSecrets :many
SELECT name, encrypted_value FROM secret ORDER BY name
`

func (q *Queries) ListSecrets(ctx context.Context) ([]Secret, error) {
	rows, err := q.db.QueryContext(ctx, listSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Secret
	for rows.Next() {
		var i Secret
		if err := rows.Scan(&i.Name, &i.EncryptedValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
