// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const createProfile = `-- name: CreateProfile :execrows

INSERT INTO profile (name, description) VALUES (?, ?)
ON CONFLICT (name) DO NOTHING
`

type CreateProfileParams struct {
	Name        string
	Description string
}

// Note: secret values are never stored in the database; they are always
// resolved from an external secret manager (e.g. 1Password).
func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createProfile, arg.Name, arg.Description)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProfile = `-- name: DeleteProfile :execrows
DELETE FROM profile WHERE name = ?
`

func (q *Queries) DeleteProfile(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProfile, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProfileVar = `-- name: DeleteProfileVar :execrows
DELETE FROM profile_var WHERE profile_id = ? AND name = ?
`

type DeleteProfileVarParams struct {
	ProfileID int64
	Name      string
}

func (q *Queries) DeleteProfileVar(ctx context.Context, arg DeleteProfileVarParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProfileVar, arg.ProfileID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProfile = `-- name: GetProfile :one
SELECT id, description FROM profile WHERE name = ?
`

type GetProfileRow struct {
	ID          int64
	Description string
}

func (q *Queries) GetProfile(ctx context.Context, name string) (GetProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getProfile, name)
	var i GetProfileRow
	err := row.Scan(&i.ID, &i.Description)
	return i, err
}

const getProfileID = `-- name: GetProfileID :one
SELECT id FROM profile WHERE name = ?
`

func (q *Queries) GetProfileID(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProfileID, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listProfileVars = `-- name: ListProfileVars :many
SELECT name, value, kind FROM profile_var WHERE profile_id = ? ORDER BY name
`

type ListProfileVarsRow struct {
	Name  string
	Value string
	Kind  string
}

func (q *Queries) ListProfileVars(ctx context.Context, profileID int64) ([]ListProfileVarsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProfileVars, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProfileVarsRow
	for rows.Next() {
		var i ListProfileVarsRow
		if err := rows.Scan(&i.Name, &i.Value, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfiles = `-- name: ListProfiles :many
SELECT name, description FROM profile ORDER BY name
`

type ListProfilesRow struct {
	Name        string
	Description string
}

func (q *Queries) ListProfiles(ctx context.Context) ([]ListProfilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProfilesRow
	for rows.Next() {
		var i ListProfilesRow
		if err := rows.Scan(&i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfileDescription = `-- name: UpdateProfileDescription :execrows
UPDATE profile SET description = ? WHERE name = ?
`

type UpdateProfileDescriptionParams struct {
	Description string
	Name        string
}

func (q *Queries) UpdateProfileDescription(ctx context.Context, arg UpdateProfileDescriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProfileDescription, arg.Description, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertProfileVar = `-- name: UpsertProfileVar :exec
INSERT INTO profile_var (profile_id, name, value, kind) VALUES (?, ?, ?, ?)
ON CONFLICT (profile_id, name) DO UPDATE SET value = excluded.value, kind = excluded.kind
`

type UpsertProfileVarParams struct {
	ProfileID int64
	Name      string
	Value     string
	Kind      string
}

func (q *Queries) UpsertProfileVar(ctx context.Context, arg UpsertProfileVarParams) error {
	_, err := q.db.ExecContext(ctx, upsertProfileVar,
		arg.ProfileID,
		arg.Name,
		arg.Value,
		arg.Kind,
	)
	return err
}
